### ISSUE TITLE
Compare Trivy dependency scanning in GitLab Dependency Scanning

### ISSUE THREAD

**Issue by tnir** [aquasecurity/trivy-ci-test#9]
On integration with GitLab Container Scanning, we are having some overlap in dependency scanning.
Compare Trivy dependency scanning in GitLab Dependency Scanning.

With the following addition to `.gitlab-ci.yml`
```
include:
  # GitLab Dependency Scanning
  - template: Dependency-Scanning.gitlab-ci.yml

dependency_scanning:
  before_script:
    - mkdir -p php-app ruby-app node-app python-app rust-app
    - cp composer_laravel.lock ./php-app/composer.lock
    - cp Gemfile_rails.lock ./ruby-app/Gemfile.lock
    - cp package-lock_react.json ./node-app/package-lock.json
    - cp Pipfile.lock ./python-app/Pipfile.lock
    - cp Cargo.lock ./rust-app/Cargo.lock
```

Following-up #7
